# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_QUIET = true
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr/share/arduino/hardware/tools/avr

BOARD_TAG     = mega2560
MONITOR_PORT  = /dev/ttyACM0
OPTIMIZATION_LEVEL = 3
include /usr/share/arduino/Arduino.mk
